# Generated by Django 4.0.4 on 2022-05-24 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pedidosa',
            new_name='Pedidos',
        ),
    ]
