# Generated by Django 4.0.4 on 2022-06-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPedidos', '0004_alter_clientes_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='numero',
            field=models.IntegerField(default=24),
            preserve_default=False,
        ),
    ]
